import type { Land } from "./Land";

// Fetch addresses for the lands from the Geoapify API
// Mutates the lands array
export const loadLandsAddresses = async (lands: Land[], apiUrl: string) => {
  console.log("🌍 ContentfulModel: fetching lands addresses ");

  // 0. Prepare request data
  const inputs = lands
    .filter((land) => land.coords)
    .map((land) => ({
      id: land.slug,
      params: { lat: land.coords![0], lon: land.coords![1] },
    }));

  // Send request (batch of coordinates to addresses)
  // Reference https://apidocs.geoapify.com/samples/batch/batch-call-javascript/

  // 1. Ask Geoapify API to convert coordinates to addresses (takes time, while pending returns 202, when done returns 200)
  let response = await fetch(apiUrl, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    body: JSON.stringify({
      api: "/v1/geocode/reverse",
      params: {
        lang: "vi",
      },
      inputs,
    }),
  });

  // 2. Get id of the batch (generated by Geoapify API and allows to check the status of the batch)
  let batchId = "";
  if (response.status === 202) {
    const body = await response.json();
    batchId = body.id;
  }

  // 3. Wait until results are ready.
  // The batch job is async: 202 = still processing, 429 = rate limited, 200 = done.
  // Use a generous attempt budget with growing back-off so a slow/busy Geoapify
  // does not abort the build (the batch can legitimately take >10s to finish).
  const maxAttempts = 60;
  let attempt = 0;
  while ((response.status === 202 || response.status === 429) && attempt < maxAttempts) {
    attempt++;

    // Back off progressively: ~5s early, growing toward a 20s cap. Honour Retry-After on 429.
    // With 60 attempts this gives the batch ~15+ minutes to finish before the build moves on.
    const retryAfter = Number(response.headers.get("retry-after"));
    const backoffMs = Number.isFinite(retryAfter) && retryAfter > 0
      ? retryAfter * 1000
      : Math.min(5000 + attempt * 1000, 20000);

    console.log(
      `🌍 Geoapify - waiting for the addresses (status ${response.status}), ` +
        `attempt #${attempt}/${maxAttempts}, retrying in ${backoffMs}ms`,
    );
    await new Promise((resolve) => setTimeout(resolve, backoffMs));

    response = await fetch(apiUrl + `&id=${batchId}`);
  }

  // 4. Get the results
  if (response.status !== 200) {
    const details = await response.text().catch(() => "<no body>");
    throw new Error(
      `🌍 Geoapify - failed to fetch addresses after ${attempt} attempts: ` +
        `status ${response.status} ${response.statusText}; body: ${details}`,
    );
  }

  const jsonResults = await response.json();

  // 5. Add addresses to the lands
  jsonResults.results.forEach((result: any) => {
    const land = lands.find((land) => land.slug === result.id);

    const address = result.result.features[0].properties.formatted;

    const adjustedAddress = (address as string).replace(", Việt Nam", "");

    if (land) land.address = adjustedAddress;
  });

  return lands;
};
