/**
 * Dev tool: extract Iconsax "Outline" SVGs for the icons the site uses and
 * generate src/components/ui/Icon.astro (a single inline-SVG icon component).
 *
 * Requires iconsax-react in node_modules (install transiently, not a dep):
 *   npm install --no-save iconsax-react
 *   node scripts/extract-icons.mjs
 *
 * Iconsax license: MIT-style (free for commercial use).
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(fileURLToPath(import.meta.url), "../..");
const SRC = path.join(ROOT, "node_modules/iconsax-react/dist/esm");
const OUT = path.join(ROOT, "src/components/ui/Icon.astro");

// semantic name -> Iconsax component (Outline variant)
const MAP = {
  location: "Location",
  message: "Messages",
  "shield-tick": "ShieldTick",
  call: "Call",
  "arrow-right": "ArrowRight",
  "arrow-left": "ArrowLeft",
  document: "TaskSquare",
  exchange: "ArrowSwapHorizontal",
  flash: "Flash",
  "trend-up": "TrendUp",
  verify: "Verify",
  people: "Profile2User",
  danger: "Danger",
  lock: "Lock",
  routing: "Routing",
  eye: "Eye",
};

const camelToKebab = (s) => s.replace(/[A-Z]/g, (m) => "-" + m.toLowerCase());

function extractOutline(componentName) {
  const file = path.join(SRC, `${componentName}.js`);
  if (!fs.existsSync(file)) return null;
  const code = fs.readFileSync(file, "utf8");
  const block = code.match(/var Outline = function[\s\S]*?\n};/);
  if (!block) return null;
  const elements = [...block[0].matchAll(/React\.createElement\("(\w+)",\s*\{([^}]*)\}/g)];
  const parts = [];
  for (const [, tag, propsRaw] of elements) {
    if (tag === "Fragment") continue;
    const attrs = [];
    // string-valued props
    for (const [, key, val] of propsRaw.matchAll(/(\w+):\s*"([^"]*)"/g)) {
      attrs.push(`${camelToKebab(key)}="${val}"`);
    }
    // color-valued props (fill: color / stroke: color)
    for (const [, key] of propsRaw.matchAll(/(\w+):\s*color\b/g)) {
      attrs.push(`${camelToKebab(key)}="currentColor"`);
    }
    parts.push(`<${tag} ${attrs.join(" ")} />`);
  }
  return parts.join("");
}

const icons = {};
const missing = [];
for (const [key, comp] of Object.entries(MAP)) {
  const svg = extractOutline(comp);
  if (!svg) {
    missing.push(`${key} (${comp})`);
    continue;
  }
  icons[key] = svg;
}

if (missing.length) {
  console.log("MISSING (fix names):", missing.join(", "));
}

const astro = `---
/**
 * Inline Iconsax (Outline) icon. Generated by scripts/extract-icons.mjs.
 * Usage: <Icon name="location" size={16} />
 */
interface Props {
  name: keyof typeof ICONS;
  size?: number | string;
  class?: string;
  label?: string;
}
const { name, size = 20, class: className, label } = Astro.props;

const ICONS = ${JSON.stringify(icons, null, 2)} as const;

const markup = ICONS[name] ?? "";
---
<svg
  xmlns="http://www.w3.org/2000/svg"
  width={size}
  height={size}
  viewBox="0 0 24 24"
  fill="none"
  class={className}
  role={label ? "img" : "presentation"}
  aria-label={label}
  aria-hidden={label ? undefined : "true"}
  set:html={markup}
/>
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, astro, "utf8");
console.log(`Wrote ${path.relative(ROOT, OUT)} with ${Object.keys(icons).length} icons.`);
