/**
 * One-off: localize the Google Fonts used by the redesign (Geist + Fraunces).
 * Downloads the woff2 subset files into public/fonts/ and writes a self-hosted
 * src/styles/fonts.css (no CDN — important for Vietnam load times). Cyrillic
 * subsets are dropped (not needed for a Vietnamese/English site).
 *
 *   node scripts/fetch-fonts.mjs
 *
 * The Google Fonts CSS was captured from the live Lovable build:
 *   Fraunces:opsz,wght@9..144,400;500;600;700  +  Geist:wght@400;500;600;700
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(fileURLToPath(import.meta.url), "../..");
const FONT_DIR = path.join(ROOT, "public/fonts");
const OUT_CSS = path.join(ROOT, "src/styles/fonts.css");
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36";
const GF_URL =
  "https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600;9..144,700&family=Geist:wght@400;500;600;700&display=swap";

const css = await (await fetch(GF_URL, { headers: { "User-Agent": UA } })).text();

fs.mkdirSync(FONT_DIR, { recursive: true });

// Match each `/* subset */ @font-face { ... }` unit.
const blockRe = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;
const out = [
  "/**",
  " * Self-hosted Geist (sans/body) + Fraunces (serif/display).",
  " * Generated by scripts/fetch-fonts.mjs from the Lovable design's font set.",
  " * Cyrillic subsets omitted. Do not edit by hand.",
  " */",
  "",
];
const downloaded = new Set();
let kept = 0;
let skipped = 0;

for (const [, subset, body] of css.matchAll(blockRe)) {
  if (subset.startsWith("cyrillic")) {
    skipped++;
    continue;
  }
  const urlMatch = body.match(/url\((https:\/\/[^)]+\.woff2)\)/);
  if (!urlMatch) continue;
  const url = urlMatch[1];
  const file = url.split("/").pop(); // unique gstatic basename
  const dest = path.join(FONT_DIR, file);

  if (!downloaded.has(url)) {
    if (!fs.existsSync(dest)) {
      const buf = Buffer.from(await (await fetch(url)).arrayBuffer());
      fs.writeFileSync(dest, buf);
      console.log(`  downloaded ${file} (${(buf.length / 1024).toFixed(1)} KB)`);
    }
    downloaded.add(url);
  }

  const localBody = body.replace(url, `/fonts/${file}`).trim();
  out.push(`/* ${subset} */`, `@font-face {`, `  ${localBody.replace(/;\s*/g, ";\n  ").trim()}`, `}`, "");
  kept++;
}

fs.writeFileSync(OUT_CSS, out.join("\n"), "utf8");
console.log(
  `\n${kept} @font-face blocks kept, ${skipped} cyrillic dropped, ${downloaded.size} files in public/fonts/.`,
);
console.log(`Wrote ${path.relative(ROOT, OUT_CSS)}`);
